[package]
name = "rustler_jieba"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "rustler_jieba"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.31.0"
jieba-rs = { version = "0.6", features = ["tfidf", "textrank"] }
