name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp_version: ['26.2.3']
        elixir_version: ['1.16.2']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache elixir deps and build
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.elixir_version }}-${{matrix.otp_version}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.elixir_version }}-${{matrix.otp_version}}-

      - name: Cache rust bulid
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            native/rustler_jieba/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Install dependencies
        run: mix deps.get

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Check for unused deps
        run: mix deps.unlock --check-unused

      - name: Compile all deps (allow warnings in deps)
        run: mix deps.compile

      - name: Compiles without warnings
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test
