# Modified from https://github.com/elixir-nx/tokenizers/blob/f560e8fe4a9748291a1d9908247ce6837635d7da/.github/workflows/rust-ci.yml

name: Rust CI (mostly lint)

on:
  push:
    branches:
      - main
    paths:
      - 'native/**'
  pull_request:
    paths:
      - 'native/**'

jobs:
  lint-rust:
    name: Lint Rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest:
          - native/rustler_jieba/Cargo.toml

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            native/ex_tokenizers/target/
            priv/native/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy


      - name: run rustfmt
        run: cargo fmt --manifest-path=${{ matrix.manifest }} --all -- --check

      - name: run clippy
        run: cargo clippy --manifest-path=${{ matrix.manifest }} -- -Dwarnings 
